services:
  client:
    container_name: client
    image: 'docker.io/naveenverma088/bookmakers_dockerized-client'
    environment:
      - WDS_SOCKET_PORT=0
      - REACT_APP_API_URL=http://35.225.46.108:3000/api
    ports:
      - 3001:80

  api:
    container_name: api
    image: 'docker.io/naveenverma088/bookmakers_dockerized-api'
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: 'mongo'
    restart: unless-stopped
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: nverma
      MONGO_INITDB_ROOT_PASSWORD: teret
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db/

  # nginx:
  #   restart: unless-stopped
  #   image: 'docker.io/naveenverma088/bookmakers_dockerized-nginx'
  #   depends_on:
  #     - api
  #     - client
  #   ports:
  #     - 3050:3050

volumes:
  mongodb_data:
